package core

// API lock: snapshots the exported surface of package core and fails when it
// drifts from the committed api.golden. This is the one contract surface every
// connector conforms to and that downstream hosts (Pilot) bind against, so a
// change here is a change to an external contract — never silent.
//
// The guard does not forbid changes; it forces them to be conscious. When a
// change is intentional, re-bless the snapshot AFTER coordinating downstream:
//
//	go test ./sdk/core -run TestPublicAPILocked -update
//
// Stdlib-only (go/parser, go/ast, go/printer) so it respects the zero-dependency
// constraint on sdk/core, and it runs as part of `go test -race ./...` in CI.

import (
	"flag"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"sort"
	"strings"
	"testing"
)

const apiGoldenPath = "api.golden"

var updateAPIGolden = flag.Bool("update", false, "re-bless the locked api.golden snapshot")

func TestPublicAPILocked(t *testing.T) {
	got := snapshotCoreAPI(t, ".")

	if *updateAPIGolden {
		if err := os.WriteFile(apiGoldenPath, []byte(got), 0o644); err != nil {
			t.Fatalf("write %s: %v", apiGoldenPath, err)
		}
		t.Logf("re-blessed %s (%d bytes)", apiGoldenPath, len(got))
		return
	}

	want, err := os.ReadFile(apiGoldenPath)
	if err != nil {
		t.Fatalf("read %s: %v\n(first run? create it: go test ./sdk/core -run TestPublicAPILocked -update)", apiGoldenPath, err)
	}
	if got != string(want) {
		t.Errorf("sdk/core public API drifted from the locked snapshot (%s):\n\n%s\n"+
			"This is the external contract Pilot binds to. If the change is intentional,\n"+
			"re-bless AFTER coordinating downstream:\n"+
			"  go test ./sdk/core -run TestPublicAPILocked -update",
			apiGoldenPath, lineDiff(string(want), got))
	}
}

// snapshotCoreAPI parses every non-test .go file in dir and renders a
// deterministic, sorted listing of the package's exported declarations.
func snapshotCoreAPI(t *testing.T, dir string) string {
	t.Helper()

	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi fs.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse %s: %v", dir, err)
	}

	var blocks []string
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				switch d := decl.(type) {
				case *ast.GenDecl:
					blocks = append(blocks, renderGenDecl(fset, d)...)
				case *ast.FuncDecl:
					if s := renderFuncDecl(fset, d); s != "" {
						blocks = append(blocks, s)
					}
				}
			}
		}
	}
	sort.Strings(blocks)

	const header = "// Public API snapshot of package core — the locked SDK contract surface.\n" +
		"// Generated by TestPublicAPILocked; DO NOT EDIT by hand.\n" +
		"// Re-bless an intentional change: go test ./sdk/core -run TestPublicAPILocked -update\n" +
		"package core\n"
	return header + "\n" + strings.Join(blocks, "\n\n") + "\n"
}

func renderGenDecl(fset *token.FileSet, d *ast.GenDecl) []string {
	var out []string
	switch d.Tok {
	case token.TYPE:
		for _, spec := range d.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || !ts.Name.IsExported() {
				continue
			}
			out = append(out, renderTypeSpec(fset, ts))
		}
	case token.CONST, token.VAR:
		kw := "const"
		if d.Tok == token.VAR {
			kw = "var"
		}
		for _, spec := range d.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, name := range vs.Names {
				if !name.IsExported() {
					continue
				}
				out = append(out, renderValueSpec(fset, kw, vs, i))
			}
		}
	}
	return out
}

func renderValueSpec(fset *token.FileSet, kw string, vs *ast.ValueSpec, i int) string {
	s := kw + " " + vs.Names[i].Name
	if vs.Type != nil {
		s += " " + typeString(fset, vs.Type)
	}
	if i < len(vs.Values) {
		s += " = " + typeString(fset, vs.Values[i])
	}
	return s
}

func renderTypeSpec(fset *token.FileSet, ts *ast.TypeSpec) string {
	switch t := ts.Type.(type) {
	case *ast.StructType:
		return renderStruct(fset, ts.Name.Name, t)
	case *ast.InterfaceType:
		return renderInterface(fset, ts.Name.Name, t)
	default:
		return "type " + ts.Name.Name + " " + typeString(fset, ts.Type)
	}
}

func renderStruct(fset *token.FileSet, name string, st *ast.StructType) string {
	var b strings.Builder
	b.WriteString("type " + name + " struct {")
	// Field order is preserved (deterministic within a single file); a reorder
	// surfaces in the diff so a human decides whether it matters.
	for _, f := range st.Fields.List {
		typ := typeString(fset, f.Type)
		tag := ""
		if f.Tag != nil {
			tag = " " + f.Tag.Value
		}
		if len(f.Names) == 0 { // embedded
			if exportedBaseName(f.Type) != "" {
				b.WriteString("\n\t" + typ + tag)
			}
			continue
		}
		for _, n := range f.Names {
			if n.IsExported() {
				b.WriteString("\n\t" + n.Name + " " + typ + tag)
			}
		}
	}
	b.WriteString("\n}")
	return b.String()
}

func renderInterface(fset *token.FileSet, name string, it *ast.InterfaceType) string {
	var b strings.Builder
	b.WriteString("type " + name + " interface {")
	for _, f := range it.Methods.List {
		if len(f.Names) == 0 { // embedded interface
			b.WriteString("\n\t" + typeString(fset, f.Type))
			continue
		}
		ft, ok := f.Type.(*ast.FuncType)
		if !ok {
			continue
		}
		for _, n := range f.Names {
			if n.IsExported() {
				b.WriteString("\n\t" + n.Name + strings.TrimPrefix(typeString(fset, ft), "func"))
			}
		}
	}
	b.WriteString("\n}")
	return b.String()
}

func renderFuncDecl(fset *token.FileSet, fn *ast.FuncDecl) string {
	if !fn.Name.IsExported() {
		return ""
	}
	sig := strings.TrimPrefix(typeString(fset, fn.Type), "func")
	if fn.Recv == nil {
		return "func " + fn.Name.Name + sig
	}
	recv := fn.Recv.List[0].Type
	if exportedBaseName(recv) == "" { // method on an unexported type
		return ""
	}
	return "func (" + typeString(fset, recv) + ") " + fn.Name.Name + sig
}

// exportedBaseName returns the exported named type at the root of e (peeling
// pointers and generic instantiations), or "" if it is unexported/unnamed.
func exportedBaseName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		if t.IsExported() {
			return t.Name
		}
	case *ast.StarExpr:
		return exportedBaseName(t.X)
	case *ast.IndexExpr:
		return exportedBaseName(t.X)
	case *ast.IndexListExpr:
		return exportedBaseName(t.X)
	}
	return ""
}

func typeString(fset *token.FileSet, e ast.Expr) string {
	var b strings.Builder
	_ = (&printer.Config{Mode: printer.RawFormat}).Fprint(&b, fset, e)
	return b.String()
}

// lineDiff renders a compact +/- view of lines that differ between want and
// got. The precise change is visible via `git diff` on api.golden after a
// -update run; this is just an at-a-glance signal in the failure message.
func lineDiff(want, got string) string {
	inWant := map[string]int{}
	for _, l := range strings.Split(want, "\n") {
		inWant[l]++
	}
	inGot := map[string]int{}
	for _, l := range strings.Split(got, "\n") {
		inGot[l]++
	}
	var b strings.Builder
	for _, l := range strings.Split(want, "\n") {
		if inGot[l] == 0 && strings.TrimSpace(l) != "" {
			b.WriteString("  - " + l + "\n")
		}
	}
	for _, l := range strings.Split(got, "\n") {
		if inWant[l] == 0 && strings.TrimSpace(l) != "" {
			b.WriteString("  + " + l + "\n")
		}
	}
	if b.Len() == 0 {
		return "  (whitespace-only difference)\n"
	}
	return b.String()
}
